import { Link } from "react-router";
import { motion } from "motion/react";
import { PillButton } from "../components/PillButton";
import { DiagonalShards } from "../components/DiagonalShards";

export function CVC() {
  const focus = "Focused on sports, wellness, longevity and human performance infrastructure.";
  const outcomes = ["Future-business scouting beyond internal R&D", "Startup pilots connected to real business units", "Strategic partnership pipeline with decision discipline", "Board-level innovation reporting and investment optionality", "AI-enabled venture operations for sourcing, diligence, IC preparation, and reporting"];
  const sprint = [
    { stage: "01", title: "Strategic Mandate", outcome: "Define future business lines, strategic themes, excluded sectors, geography, decision rights, and success metrics." },
    { stage: "02", title: "Governance & IC", outcome: "Build approval gates, IC rhythm, roles, conflict rules, pilot-to-investment logic, memo format, and reporting cadence." },
    { stage: "03", title: "Budget & Operating Model", outcome: "Separate operating budget, scouting, pilot budget, capital deployment, team roles, advisors, and reporting workspace." },
    { stage: "04", title: "Startup Warehouse", outcome: "Create the sourcing map, intake flow, scoring model, longlist, priority shortlist, founder outreach, and diligence queue." },
    { stage: "05", title: "First IC Package", outcome: "Prepare IC memos, red flags, pilot/investment recommendations, KPI dashboard, decision log, and next sprint plan." },
  ];
  const deliverables = ["CVC mandate and investment policy", "Sports / wellness / longevity / human performance thesis map", "Startup warehouse and sourcing dashboard", "Founder intake and scoring framework", "Pilot-to-investment operating workflow", "IC memo templates and decision log", "Budget and use-of-funds schedule", "KPI dashboard and board reporting pack", "Data room and compliance checklist", "Conflict, allocation, and partner-access notes"];
  const fit = ["Corporate groups", "Family-owned groups", "Sports and wellness operators", "Longevity and health-adjacent platforms", "Human-performance infrastructure companies"];
  const List = ({ items }: { items: string[] }) => <div className="space-y-3">{items.map((item) => <div key={item} className="flex gap-3 text-[13px] sm:text-[14px] text-muted-foreground/70 font-light leading-relaxed"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-foreground/45" /><span>{item}</span></div>)}</div>;

  return <div className="pt-24 sm:pt-28 lg:pt-32 pb-16 sm:pb-20 lg:pb-24 px-6 sm:px-8 lg:px-12"><div className="max-w-[1200px] mx-auto">
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="mb-16 sm:mb-20 lg:mb-24"><div className="relative rounded-[28px] sm:rounded-[32px] bg-gradient-to-br from-[#1a1d26]/70 via-[#12141a]/85 to-[#1a1d26]/70 border border-white/[0.06] backdrop-blur-2xl overflow-hidden"><DiagonalShards /><div className="relative px-6 sm:px-10 lg:px-12 py-10 sm:py-12"><div className="inline-flex items-center gap-2 mb-5"><div className="w-1.5 h-1.5 rounded-full bg-foreground/70" /><span className="text-[12px] sm:text-[13px] text-muted-foreground/60 font-light uppercase tracking-wider">CVC launch</span></div><h1 className="text-[36px] sm:text-[48px] lg:text-[64px] font-light tracking-tight text-foreground/95 mb-5 sm:mb-6 leading-tight max-w-4xl">Turn corporate innovation interest into a managed venture pipeline.</h1><p className="text-[14px] sm:text-[16px] lg:text-[17px] text-muted-foreground/70 font-light leading-relaxed max-w-3xl mb-4">We help corporate and family-owned groups launch CVC programs that connect strategic priorities to startup scouting, pilots, IC governance, reporting, and future business-building options.</p><p className="text-[13px] sm:text-[15px] text-foreground/78 font-light leading-relaxed max-w-3xl mb-8 sm:mb-10">{focus}</p><div className="flex flex-wrap items-center gap-3 sm:gap-4"><PillButton to="/contact?interest=cvc" variant="primary" className="w-full sm:w-auto justify-center">Start CVC launch sprint</PillButton><PillButton to="/contact?interest=cvc-launch-pack" variant="secondary" className="w-full sm:w-auto justify-center">Request CVC launch pack</PillButton><Link to="/platform" className="text-[13px] text-muted-foreground/60 hover:text-foreground/85 transition-colors">See Fund OS →</Link></div></div></div></motion.div>
    <section className="mb-16 sm:mb-20 lg:mb-24 rounded-[26px] sm:rounded-[28px] bg-gradient-to-br from-[#1a1d26]/45 via-[#12141a]/55 to-[#1a1d26]/45 border border-white/[0.06] p-6 sm:p-10"><div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12"><div className="lg:col-span-5"><span className="text-[12px] text-muted-foreground/50 font-light uppercase tracking-wider">Strategic value</span><h2 className="text-[26px] sm:text-[34px] font-light tracking-tight text-foreground/90 mt-3 mb-4">CVC should create business options, not just startup exposure.</h2><p className="text-[13px] sm:text-[15px] text-muted-foreground/70 font-light leading-relaxed">The program is strongest when startup scouting is connected to real business units, pilot budgets, strategic KPIs, and board-level decisions.</p></div><div className="lg:col-span-7"><List items={outcomes} /></div></div></section>
    <section className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-16 sm:mb-20 lg:mb-24"><div className="rounded-[26px] sm:rounded-[28px] bg-gradient-to-br from-[#1a1d26]/40 via-[#12141a]/50 to-[#1a1d26]/40 border border-white/[0.06] p-6 sm:p-8"><h2 className="text-[24px] sm:text-[30px] font-light tracking-tight text-foreground/90 mb-6">Best fit</h2><List items={fit} /></div><div className="rounded-[26px] sm:rounded-[28px] bg-gradient-to-br from-[#1a1d26]/40 via-[#12141a]/50 to-[#1a1d26]/40 border border-white/[0.06] p-6 sm:p-8"><h2 className="text-[24px] sm:text-[30px] font-light tracking-tight text-foreground/90 mb-6">Operating principle</h2><p className="text-[13px] sm:text-[15px] text-muted-foreground/70 font-light leading-relaxed">CVC is positioned as strategic operating infrastructure: a repeatable way to see future businesses, run pilots, document decisions, and decide when investment makes strategic sense.</p></div></section>
    <section className="mb-16 sm:mb-20 lg:mb-24"><h2 className="text-[26px] sm:text-[32px] lg:text-[36px] font-light tracking-tight text-foreground/90 mb-8 sm:mb-12">90-Day CVC Launch Sprint</h2><div className="space-y-4 sm:space-y-5">{sprint.map((step, index) => <motion.div key={step.stage} initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.06 }} className="grid grid-cols-1 md:grid-cols-12 gap-4 md:gap-8 rounded-[22px] sm:rounded-[24px] bg-gradient-to-br from-[#1a1d26]/50 via-[#12141a]/60 to-[#1a1d26]/50 border border-white/[0.06] p-6 sm:p-8"><div className="md:col-span-2 text-[12px] text-muted-foreground/42 font-light uppercase tracking-wider">Step {step.stage}</div><div className="md:col-span-4 text-[20px] sm:text-[24px] text-foreground/90 font-light tracking-tight">{step.title}</div><div className="md:col-span-6 text-[13px] sm:text-[14px] text-muted-foreground/70 font-light leading-relaxed">{step.outcome}</div></motion.div>)}</div></section>
    <section className="rounded-[26px] sm:rounded-[28px] bg-gradient-to-br from-[#1a1d26]/40 via-[#12141a]/50 to-[#1a1d26]/40 border border-white/[0.06] p-6 sm:p-10"><div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12"><div className="lg:col-span-5"><h2 className="text-[26px] sm:text-[34px] font-light tracking-tight text-foreground/90 mb-4">What the corporate group receives</h2><p className="text-[13px] sm:text-[15px] text-muted-foreground/70 font-light leading-relaxed">A practical CVC operating package that can be reviewed by owners, board members, legal, finance, business units, and future investment committee members.</p></div><div className="lg:col-span-7 grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">{deliverables.map((item) => <div key={item} className="rounded-[18px] bg-white/[0.025] border border-white/[0.05] p-5 text-[13px] sm:text-[14px] text-muted-foreground/70 font-light leading-relaxed">{item}</div>)}</div></div></section>
  </div></div>;
}
