import { Link } from "react-router";
import { motion } from "motion/react";
import { DiagonalShards } from "../components/DiagonalShards";

export function CVCLaunchPack() {
  const sprint = [
    { phase: "Weeks 1–2", title: "Mandate", outcome: "Strategic priorities, thesis, governance, budget assumptions, and decision rights." },
    { phase: "Weeks 3–5", title: "Setup", outcome: "IC rhythm, startup warehouse, scoring model, data room, and reporting template." },
    { phase: "Weeks 6–10", title: "Pipeline", outcome: "Founder outreach, market map, shortlist, first diligence notes, and pilot candidates." },
    { phase: "Weeks 11–12", title: "First IC", outcome: "IC pack, recommendations, pilot/investment decision points, and next-quarter roadmap." },
  ];
  const deliverables = ["CVC mandate", "Investment policy", "Startup warehouse", "IC memo template", "KPI dashboard", "First pipeline shortlist", "Risk register", "Board-level launch memo"];
  const corporateFit = ["Clear strategic sectors", "Budget owner and executive sponsor", "Ability to run pilots", "Interest in future M&A or strategic partnerships", "Willingness to use disciplined governance"];
  const handlePrint = () => window.print();

  return (
    <div className="pt-24 sm:pt-28 lg:pt-32 pb-16 sm:pb-20 lg:pb-24 px-6 sm:px-8 lg:px-12">
      <div className="max-w-[1200px] mx-auto">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="mb-16 sm:mb-20 lg:mb-24">
          <div className="relative rounded-[28px] sm:rounded-[32px] bg-gradient-to-br from-[#1a1d26]/70 via-[#12141a]/85 to-[#1a1d26]/70 border border-white/[0.06] backdrop-blur-2xl overflow-hidden"><DiagonalShards /><div className="relative px-6 sm:px-10 lg:px-12 py-10 sm:py-12"><div className="inline-flex items-center gap-2 mb-5"><div className="w-1.5 h-1.5 rounded-full bg-foreground/70" /><span className="text-[12px] sm:text-[13px] text-muted-foreground/60 font-light uppercase tracking-wider">Corporate one-pager</span></div><h1 className="text-[36px] sm:text-[48px] lg:text-[64px] font-light tracking-tight text-foreground/95 mb-5 sm:mb-6 leading-tight max-w-4xl">CVC Launch Pack</h1><p className="text-[14px] sm:text-[16px] lg:text-[17px] text-muted-foreground/70 font-light leading-relaxed max-w-3xl mb-8 sm:mb-10">A board-friendly one-pager for corporate groups that want to launch a venture function, scout future businesses, run startup pilots, and create a disciplined strategic investment pipeline.</p><div className="flex flex-wrap gap-3 sm:gap-4 print:hidden"><button onClick={handlePrint} className="inline-flex items-center justify-center rounded-full border border-white/10 bg-white/10 px-5 py-2.5 sm:px-6 sm:py-3 text-[13px] sm:text-[14px] text-foreground/95 font-light hover:bg-white/15 transition-colors w-full sm:w-auto">Print / save as PDF</button><Link to="/contact?interest=cvc" className="inline-flex items-center justify-center rounded-full border border-white/5 px-5 py-2.5 sm:px-6 sm:py-3 text-[13px] sm:text-[14px] text-muted-foreground/80 font-light hover:bg-white/5 hover:text-foreground/90 transition-colors w-full sm:w-auto">Discuss CVC mandate</Link></div></div></div>
        </motion.div>
        <section className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-16 sm:mb-20 lg:mb-24"><div className="rounded-[26px] sm:rounded-[28px] bg-gradient-to-br from-[#1a1d26]/40 via-[#12141a]/50 to-[#1a1d26]/40 border border-white/[0.06] p-6 sm:p-8"><h2 className="text-[24px] sm:text-[30px] font-light tracking-tight text-foreground/90 mb-6">Best-fit corporate profile</h2><div className="space-y-3">{corporateFit.map((item) => <div key={item} className="flex gap-3 text-[13px] sm:text-[14px] text-muted-foreground/70 font-light leading-relaxed"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-foreground/45" /><span>{item}</span></div>)}</div></div><div className="rounded-[26px] sm:rounded-[28px] bg-gradient-to-br from-[#1a1d26]/40 via-[#12141a]/50 to-[#1a1d26]/40 border border-white/[0.06] p-6 sm:p-8"><h2 className="text-[24px] sm:text-[30px] font-light tracking-tight text-foreground/90 mb-6">Launch deliverables</h2><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{deliverables.map((item) => <div key={item} className="rounded-[16px] bg-white/[0.025] border border-white/[0.05] p-4 text-[13px] sm:text-[14px] text-muted-foreground/70 font-light leading-relaxed">{item}</div>)}</div></div></section>
        <section className="mb-16 sm:mb-20 lg:mb-24"><h2 className="text-[26px] sm:text-[32px] lg:text-[36px] font-light tracking-tight text-foreground/90 mb-8 sm:mb-12">90-day launch sprint</h2><div className="space-y-4 sm:space-y-5">{sprint.map((item, index) => <motion.div key={item.phase} initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.06 }} className="grid grid-cols-1 md:grid-cols-12 gap-4 md:gap-8 rounded-[22px] sm:rounded-[24px] bg-gradient-to-br from-[#1a1d26]/50 via-[#12141a]/60 to-[#1a1d26]/50 border border-white/[0.06] p-6 sm:p-8"><div className="md:col-span-2 text-[12px] text-muted-foreground/42 font-light uppercase tracking-wider">{item.phase}</div><div className="md:col-span-4 text-[20px] sm:text-[24px] text-foreground/90 font-light tracking-tight">{item.title}</div><div className="md:col-span-6 text-[13px] sm:text-[14px] text-muted-foreground/70 font-light leading-relaxed">{item.outcome}</div></motion.div>)}</div></section>
        <section className="rounded-[26px] sm:rounded-[28px] bg-gradient-to-br from-[#1a1d26]/40 via-[#12141a]/50 to-[#1a1d26]/40 border border-white/[0.06] p-6 sm:p-10"><div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12"><div className="lg:col-span-5"><h2 className="text-[26px] sm:text-[34px] font-light tracking-tight text-foreground/90 mb-4">Expected executive outcome</h2><p className="text-[13px] sm:text-[15px] text-muted-foreground/70 font-light leading-relaxed">By the end of the sprint, the corporate group has a clear venture mandate, operating rhythm, first startup shortlist, IC-ready materials, and a repeatable path from scouting to pilots and investment decisions.</p></div><div className="lg:col-span-7"><Link to="/cvc" className="inline-flex items-center justify-center rounded-full border border-white/10 bg-white/10 px-5 py-2.5 sm:px-6 sm:py-3 text-[13px] sm:text-[14px] text-foreground/95 font-light hover:bg-white/15 transition-colors w-full sm:w-auto">View full CVC program page</Link></div></div></section>
      </div>
    </div>
  );
}
