import { motion } from "motion/react";
import { PillButton } from "../components/PillButton";
import { DiagonalShards } from "../components/DiagonalShards";

export function Fund() {
  const offers = [
    ["DAO Fund Access", "$10,000–$100,000", "For smaller LPs who want early access to the shared venture pipeline.", "Pooled DAO-style fund access through a managed community investment wrapper.", "2% of subscribed capital, minimum $250, capped at $2,000", "3% p.a. on committed or subscribed capital", ["Smaller tickets", "Community access", "Deal-flow exposure"]],
    ["Custom CVC Program", "From $2,000,000", "For corporate groups that want their own venture arm and strategic startup pipeline.", "Dedicated CVC mandate with scouting, pilots, IC process, reporting, and operating model.", "$100,000–$150,000 for launch architecture, legal coordination, operating model, data room, and first pipeline sprint", "3% p.a. of program capital, with a $15,000/month operating minimum", ["Strategic innovation", "M&A pipeline", "Board-level reporting"]],
    ["Classic VC Fund Access", "$500,000–$2,000,000", "For LPs who want diversified exposure to a classic venture fund.", "BVI fund vehicle with Delaware management company / GP platform, subject to final counsel and onboarding.", "1% of commitment, minimum $5,000, capped at $20,000", "2% p.a. during the investment period, with step-down mechanics defined in documents", ["Classic LP participation", "Diversified exposure", "Quarterly reporting"]],
    ["Dedicated Mono-LP Fund", "From $10,000,000", "For a family office, corporate group, or strategic investor that wants a bespoke mandate.", "Dedicated BVI mono-LP fund with custom mandate, reporting, and governance package.", "From $200,000 for vehicle formation, fund documents, onboarding, operating model, and launch coordination", "2% p.a., with a $200,000/year minimum management fee", ["Full mandate control", "Custom thesis", "Dedicated reporting"]],
  ];
  const thesis = [["CIS technical talent, global packaging", "We source from under-commercialized technical ecosystems and help founders become investable for international capital and partners."], ["MENA, US, and EU commercialization corridors", "We focus on markets where corporate buyers, family offices, accelerators, and strategic capital can accelerate adoption."], ["AI-enabled venture operations", "Our Fund OS supports sourcing, scoring, memo generation, IC workflows, portfolio monitoring, and LP reporting."]];
  const stack = [["Management layer", "maksat.PRO venture platform and Delaware management company stack"], ["Fund layer", "BVI, CVC, DAO-style, SPV, or mono-LP structures depending on ticket and mandate"], ["Operating layer", "Sourcing, due diligence, legal coordination, reporting, and portfolio support"], ["Compliance layer", "KYC/AML, data room discipline, and jurisdiction-specific counsel review"]];
  return <div className="pt-24 sm:pt-28 lg:pt-32 pb-16 sm:pb-20 lg:pb-24 px-6 sm:px-8 lg:px-12"><div className="max-w-[1200px] mx-auto">
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="mb-16 sm:mb-20 lg:mb-24"><div className="relative rounded-[28px] sm:rounded-[32px] bg-gradient-to-br from-[#1a1d26]/70 via-[#12141a]/85 to-[#1a1d26]/70 border border-white/[0.06] backdrop-blur-2xl overflow-hidden"><DiagonalShards /><div className="relative px-6 sm:px-10 lg:px-12 py-10 sm:py-12"><div className="inline-flex items-center gap-2 mb-5"><div className="w-1.5 h-1.5 rounded-full bg-foreground/60" /><span className="text-[12px] sm:text-[13px] text-muted-foreground/60 font-light uppercase tracking-wider">Capital products</span></div><h1 className="text-[36px] sm:text-[48px] lg:text-[64px] font-light tracking-tight text-foreground/95 mb-5 sm:mb-6 leading-tight max-w-4xl">Four entry points into the maksat.PRO venture platform</h1><p className="text-[14px] sm:text-[16px] lg:text-[17px] text-muted-foreground/70 font-light leading-relaxed max-w-3xl mb-8 sm:mb-10">We structure access by capital size and governance need: small-ticket pooled access, custom CVC mandates, classic venture fund participation, and bespoke mono-LP vehicles.</p><div className="flex flex-wrap items-center gap-3 sm:gap-4"><PillButton variant="primary" className="w-full sm:w-auto justify-center">Discuss allocation</PillButton><PillButton variant="secondary" className="w-full sm:w-auto justify-center">Request LP materials</PillButton></div></div></div></motion.div>
    <section className="mb-16 sm:mb-20 lg:mb-24"><h2 className="text-[26px] sm:text-[32px] lg:text-[36px] font-light tracking-tight text-foreground/90 mb-4">LP Product Ladder</h2><p className="text-[13px] sm:text-[15px] text-muted-foreground/60 font-light leading-relaxed max-w-3xl mb-8 sm:mb-12">The numbers below are indicative commercial terms for discussion. Final economics, legal wrappers, eligibility, and timing depend on professional review.</p><div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-6">{offers.map(([title,ticket,audience,structure,setup,management,bestFor], index) => <motion.div key={title as string} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }} className="rounded-[24px] sm:rounded-[28px] bg-gradient-to-br from-[#1a1d26]/50 via-[#12141a]/60 to-[#1a1d26]/50 border border-white/[0.06] p-6 sm:p-8 hover:border-white/[0.1] transition-all duration-500"><div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4 mb-6"><div><div className="text-[11px] text-muted-foreground/40 font-light uppercase tracking-wider mb-3">{ticket as string}</div><h3 className="text-[24px] sm:text-[30px] font-light tracking-tight text-foreground/92 leading-tight">{title as string}</h3></div><div className="px-3 py-1 rounded-full bg-white/[0.03] border border-white/[0.06] text-[11px] text-muted-foreground/60 font-light whitespace-nowrap">Offer {String(index + 1).padStart(2, "0")}</div></div><p className="text-[13px] sm:text-[14px] text-muted-foreground/70 font-light leading-relaxed mb-6">{audience as string}</p><div className="space-y-4 mb-6">{[["Structure", structure], ["Setup fee", setup], ["Management fee", management]].map(([label, value]) => <div key={label as string}><div className="text-[11px] text-muted-foreground/40 font-light uppercase tracking-wider mb-1">{label as string}</div><p className="text-[13px] sm:text-[14px] text-foreground/80 font-light leading-relaxed">{value as string}</p></div>)}</div><div className="flex flex-wrap gap-2">{(bestFor as string[]).map((item) => <span key={item} className="px-3 py-1 rounded-full bg-white/[0.03] border border-white/[0.05] text-[11px] sm:text-[12px] text-muted-foreground/60 font-light">{item}</span>)}</div></motion.div>)}</div></section>
    <section className="mb-16 sm:mb-20 lg:mb-24"><h2 className="text-[26px] sm:text-[32px] lg:text-[36px] font-light tracking-tight text-foreground/90 mb-4">Investment Thesis</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-4 sm:gap-6">{thesis.map(([title, description], index) => <motion.div key={title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.1 }} className="rounded-[22px] sm:rounded-[24px] bg-gradient-to-br from-[#1a1d26]/50 via-[#12141a]/60 to-[#1a1d26]/50 border border-white/[0.06] p-6 sm:p-8"><div className="text-[11px] text-muted-foreground/40 font-light uppercase tracking-wider mb-4">Thesis {String(index + 1).padStart(2, "0")}</div><h3 className="text-[20px] sm:text-[22px] font-light tracking-tight text-foreground/90 mb-3">{title}</h3><p className="text-[13px] sm:text-[14px] text-muted-foreground/70 font-light leading-relaxed">{description}</p></motion.div>)}</div></section>
    <section className="mb-16 sm:mb-20 lg:mb-24"><h2 className="text-[26px] sm:text-[32px] lg:text-[36px] font-light tracking-tight text-foreground/90 mb-8 sm:mb-12">Platform Stack</h2><div className="rounded-[26px] sm:rounded-[28px] bg-gradient-to-br from-[#1a1d26]/40 via-[#12141a]/50 to-[#1a1d26]/40 border border-white/[0.06] overflow-hidden"><div className="divide-y divide-white/[0.04]">{stack.map(([label, value], index) => <motion.div key={label} initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }} className="grid grid-cols-1 md:grid-cols-3 gap-3 md:gap-8 p-5 sm:p-6"><div className="text-[12px] sm:text-[13px] text-muted-foreground/50 font-light uppercase tracking-wider">{label}</div><div className="md:col-span-2 text-[13px] sm:text-[14px] text-foreground/80 font-light leading-relaxed">{value}</div></motion.div>)}</div></div></section>
  </div></div>;
}
